name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd tls
        docker build . --file Dockerfile --tag wangxunqi/v2ray:latest
    - name: Run the Docker image
      run: docker run -d -p 443:443 wangxunqi/v2ray:latest && curl -k https://127.0.0.1
