name: Geph4

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y
        export PATH=$HOME/.cargo/bin:$PATH
        cargo install cross
        git clone https://github.com/geph-official/geph4.git
        cd geph4/
        cross build --release --target aarch64-linux-android --manifest-path=geph4-client/Cargo.toml
    - uses: actions/upload-artifact@master
      with:
        name: geph4-client
        path: target/aarch64-linux-android/release/geph4-client
