name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - env:
        GOOS: android
        GOARCH: arm
        CGO_ENABLED: 0
      run: |
        git clone https://github.com/v2ray/v2ray-core.git $HOME/src
        cd $HOME/src
        go get -u v2ray.com/core/...
        cd $HOME/src/main
        go build -o $HOME/v2ray
        cd $HOME/src/infra/control/main
        go build -o $HOME/v2ctl
