name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - env:
        GOOS: linux
        GOARCH: arm64
        CGO_ENABLED: 0
      run: |
        git clone https://github.com/v2ray/v2ray-core.git $(go env GOPATH)/src/v2ray.com/core
        go get -u v2ray.com/core/...
        cd $(go env GOPATH)/src/v2ray.com/core/main
        go build -o $HOME/v2ray
        cd $(go env GOPATH)/src/v2ray.com/core/infra/control/main
        go build -o $HOME/v2ctl
